### PR TITLE
Private Events - Review

### PR DESCRIPTION
**Pull request by udberg**
In this project, We built a private Eventbrite which allows users to create events and then manage user signups. Users can create events and send invitations and parties. Events take place at a specific date and at a location (which you can just store as a string, like “Andy’s House”).

### CODE REVIEW

**Review by enaburekhan — COMMENTED** [review]
# Status: Invalid
**Hi team!
Friendly reminder! this project is marked invalid due to the failing linters check. This is a new requirement from microverse. kindly check [here](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-#). Please submit a new review when you are ready.**

Happy Coding!
Eric Enaburekhan

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Your project is professionally done 👏.**

### Highlights

- **It passes project-specific requirements.**
- **The unit tests are well written.**
- **The README is professional.**

### Mandatory Requirements.

1). **Add `.DS_Store `file into `.gitignore` file and remove it from the git tree.**

2). **Remove `if` logic statements in the following view files:**

- `headers/_default.html.erb`.
- `events/_event_actionable.html.erb`.
- `events/show.html.erb`.

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Request Changes 🛑♻**

<hr>

Hello team. I must say! You've done fascinating work designing this app and completing its specifications. Well done. However, there are still very small changes to do before getting it approved. 😊🙏

- [x] Well done mentioning the ```rails webpacker:install``` CLI, but the ```rails db:create db:migrate``` is not optional in order to run the app's server properly. Kindly adjust that.
- [x] I see that you still have logic in your views. Please, and as my teammate mentioned in the previous review, move any logical code from the views into the application helpers, then reassign it in the views as methods.

<hr>

## **OPTIONAL but Highly Recommended**

- Great work you did on displaying messages to the users. However, I cannot exit them when I click the 'x' button. Kindly adjust that in order to leave this great feature flawlessly.
- A user shouldn't be able to attend the already finished (past) events. Please take 5 mins of your time to fix this issue.

<hr>

Kindly do the required changes before submitting another review, and feel free to do the recommended ones if you found them rational and helpful. 😊👍

Good luck and happy coding 👨‍💻💻

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Hello Team :wave:
Status: Changes Required :recycle:

Great job :clap:
I like your design, it looks very nice. Your project covers all the Behavior required, your unit tests and integration is perfect but before approving this project let's cover a few details together to make your project better :blush: :arrow_double_down: . I am sure that it will not take a lot of time:
REQUIRED:

- [x] Configure your `linter` correctly:

As you can see here, `rubocop` file is missing. Please, add it.

- [x] Add `.DS_Store` file into `.gitignore` file and remove it from the git tree as previous TSEs said.
- [x] `rails db:create db:migrate` **is not optional**. Please correct your `readme file.`
- [x] Add `screenshot` to make it professional :smile: 
- [x] let's organize your code a bit: View logic should never be in the views, it should be in helper methods. Make sure all those if/else statements are inside helper methods.
- [x] `Primary key` of `events table` must be an `Integer`.
- [x] the `event_attendances` table must have column `event_id` of type `integer`
- [x] an **`index`** for **`event_id`** column is added.

That's it, you can submit another code review request after making these changes
With all my respect :pray:

Rindra Josia

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
You did a good job working on the suggested changes. Readme was updated, unnecessary folders added to `.gitignore`, rubocop added to gemfile as requested. Well done!

Merge and proceed to the next project.


### Martin Afani

**Pull request merged**
